### ISSUE TITLE
Elemental Heart Particles no longer play when hitting enemies with Melee attacks

### ISSUE THREAD

**Issue by Farcr** [FoundryMC/Alembic#12]
Intended behavior: (Alembic 1.0)
![2024-01-13_23 06 14](https://github.com/FoundryMC/Alembic/assets/40238086/ef7c1354-c6c7-491a-b15c-190e866ff9ea)
Current behavior: (Alembic 1.0.5)
![2024-04-30_17 47 38](https://github.com/FoundryMC/Alembic/assets/40238086/57b22adb-c19f-417d-b98d-de73135a4504)

Extra context: heart numbers are working correctly. first image has a non-fully charged attack, which is why it has only one heart of physical damage. ignore the number difference.

**Comment by dhyces** [comment]
Looks to be fixed in latest, so closing
