### ISSUE TITLE
Shields do not block physical (and possibly any) damage correctly

### ISSUE THREAD

**Issue by Farcr** [FoundryMC/Alembic#13]
Blocking with a shield still causes damage to be applied to you - it's only slightly reduced. the hit sound, block sound or any sound at all isn't played, but health is slowly but steadily removed. Very high priority issue.

**Comment by dhyces** [comment]
The removal of the `mob_attack_no_aggro`, `mob_attack`, and `player_attack` damage types from the base overrides broke this

**Comment by dhyces** [comment]
Fixed by [1d5c73](https://github.com/FoundryMC/Alembic/commit/1d5c73e63d2b863497171fb6772fd367753f12cf)
