### ISSUE TITLE
Damage gets doubled randomly

### ISSUE THREAD

**Issue by pafeuu** [FoundryMC/Alembic#22]
Hey cant really figure out what would be causing the issue. Alembic is an important part of my pack so I really dont want to remove it but the bug is completely breaking the balance :(

Alembic version 1.1
Minecraft version 1.20.1
Pack name: Druidic Quest Expert

Couldn't find anything related to alembic in the logs but the damage works just fine without alembic

**Comment by dhyces** [comment]
Do you have the `owner_attribute_projectiles` config setting enabled?

**Comment by amoooooo** [comment]
can you also confirm its not a critical strike? it's changed to be random by AttributeLib, which we rely on for tooltip stuff. set the crit chance attribute to 0 and confirm it still happens (if it doesn't, its a crit)

**Comment by pafeuu** [comment]
> Do you have the `owner_attribute_projectiles` config setting enabled?

disabled


> can you also confirm its not a critical strike? it's changed to be random by AttributeLib, which we rely on for tooltip stuff. set the crit chance attribute to 0 and confirm it still happens (if it doesn't, its a crit)

im 99% sure its not a crit but will test that.

I forgot to mention but the damage isn't doubled it just happens twice(sometimes with a little different numbers too)
I'am using TslatEntityStatus to check that

**Comment by pafeuu** [comment]
Still happening even with 0% crit chance

**Comment by briarss** [comment]
Oh if the TES damage numbers pop up twice, thats a known issue with TES's compat - if its not actually doubled there's nothing we can do, its a TES bug that we cannot find the cause of

**Comment by pafeuu** [comment]
TES damage numbers are correct its not just visual bug. fist deals 2 damage and you can oneshot zombies with stone axe etc.

**Comment by pafeuu** [comment]
Turns out the bug was caused by me copying the base damage types into my datapack. Which I guess made it so duplicate damage types were loaded instead of overriding?
